export const RECIPE_DATA = [
  {
    id: 137739,
    recipeName: 'arriba  baked winter squash mexican style',
    cookTime: 2060,
    description:
      'autumn is my favorite time of year to cook! this recipe can be prepared either spicy or sweet, your choice!two of my posted mexican-inspired seasoning mix recipes are offered as suggestions.',
    ingredients: [
      'winter squash',
      'mexican seasoning',
      'mixed spice',
      'honey',
      'butter',
      'olive oil',
      'salt',
    ],
    steps: ['step 1', 'step 2', 'step 3'],
  },
  {
    id: 45,
    recipeName: 'chocolate raspberry ruffle cake',
    cookTime: 1080,
    description:
      "alice medrich recipe, found in baking with julia. amazing, amazing cake recipe. this took me an entire long day to make, but it is well worth it. i'd also advise practice before you make it for company--i am glad i practiced on my husband once before i make it for a crowd. absolutely decadent recipe by the queen of chocolate. see directions below for needed equipment.",
    steps: [
      'first of all: these are not typical directions , but you need to know about needed equipment before attempting this cake',
      'here it is:',
      '8-inch round cake pan , at least 2 inches high',
      '8-inch round cake pan with removable bottom or 8-inch springform pan',
      'untreated heavy-duty jelly-roll pans',
      'rubber spatula , offset spatula , and flexible 8-inch metal icing spatula',
      'decorating turntable , lazy susan , or inverted round cake pan',
      'ridged plastic shelf liner , freezer paper , or 055 mylar',
      'parchment paper and waxed paper',
      'making the cake:',
      "position a rack in the lower third of the oven or just below the center of the oven and preheat the oven to 350f fit the bottom of an 8-inch round cake pan , one at least 2 inches high , with parchment paper and set aside', \"pour the clarified butter into a 1-quart bowl and stir in the vanilla extract , if you're using it\", 'the butter must be hot when added to the batter , so either keep the bowl in a skillet of hot water or reheat at the last minute",
      'although the flour and cocoa were sifted before they were measured , they need to be triple-sifted together',
      'sift or sieve the flour and cocoa together 3 times , then set sifter on a plate or piece of waxed paper and return the dry ingredients to the sifter',
      'keep close at hand',
      'whisk the eggs and sugar together in a large heatproof bowl or the bowl of a heavy-duty mixer',
      'set the bowl over direct heat or in a pan of barely simmering water and heat the eggs , whisking constantly , until they are warm to the touch',
      'remove the bowl from the heat and , working with a heavy-duty mixer fitted with the whisk attachment , beat the eggs at high speed until they are cool , have tripled in volume , and hold a ribbon when the whisk is lifted',
      'sift one third of the dry ingredients over the eggs and , using a large rubber spatula , fold in gently but thoroughly',
      'when the color of the batter is almost uniform , fold in the rest of the flour-cocoa mixture',
      'spoon about 1 cup of the batter into the hot clarified butter add fold together until well blended',
      "spoon this over the batter and , using the large rubber spatula , gently fold into the batter', \"spoon the batter into the pan: there's no need to smooth the top or rap the pan on the counter , as is sometimes done with foam-based cakes\", 'bake the cake for 25-30 minutes , or until top of the cake springs back when pressed gently",
      'transfer the pan to a rack and let the cake cool in the pan',
      'when the cake is completely cool , run a small knife around the sides of the pan to release the cake and unmold onto a rack',
      'invert right side up onto a piece of parchment paper',
      'preparing the chocolate:',
      "the chocolate is going to be spread and then scraped into ruffles from four baking pans', \"if you don't have enough pans , you can make the ruffles in 2 batches\", 'choose heavy-duty jelly-roll pans that are neither warped nor dented , neither nonstick non treated with special coatings",
      'keep them close at hand',
      'melt the chocolate in a heatproof bowl set in a skillet of barely simmering water , in the top of a double boiler over an inch of simmering water , or in a microwave oven sat at medium power',
      'stir the chocolate regularly until it is fully melted',
      'smooth , and 115f to 120f',
      'hold the bottom of one of the baking sheets over a burner and , moving it back and forth , heat it until it is warm but not hot enough to burn your fingers',
      'put the baking pan upside down on a flat surface and pour on about 1 / 3 cup of the chocolate',
      'use an offset spatula to spread the chocolate thinly and evenly over the bottom of the baking pan: the chocolate will only be about 1 / 16 inch thick',
      'refrigerate the pan for at least 30 minutes , or for as long as several hours , depending on your schedule',
      'repeat with rest of the chocolate and the other baking pans',
      'making the ruffles:',
      'to shape the ruffles , work with one baking pan of chocolate at a time',
      'remove a pan of chocolate from the refrigerator and leave it at room temperature to warm gradually until it is pliable enough to be scraped',
      'place the baking pan on a counter in front of you , a short side braced against your body',
      'hold the end of the blade of a then , flexible 8-inch metal icing spatula in your left hand and , with your right hand , grab the blade close to the handle',
      "you should have 4 to 5 inches of blade exposed and available for ruffling', \"using the top left corner of the pan as your staring point and imagining that corner of the pan as 12 o'clock , position your left hand in that corner , and your right at 2 o'clock\", 'press the edge of the blade against the chocolate at a very shallow angle , as if you were going to slide the spatula blade under the chocolate', \"now slide the blade forward , moving your right hand down to 5 o'clock and then pivoting the blade to the left , all the way to the edge of the pan\", 'as your right hand is moving down , so is your left , although not as far - your left hand will move down 4 to 5 inches', \"this is an important point - if you don't move your left hand down , you'll end up with tight curls of chocolate rather than ruffles\", 'as you scrape and ruffle the chocolate against the blade and then make the pivot , the chocolate will gather against the blade -- use your left hand to pinch the chocolate so that the ruffles form a fan and the pinched part is a little handle', \"you've completed one ruffle\", 'as you make each ruffle , place it on a parchment or waxed paper-lined baking sheet and refrigerate",
      "when the ruffles harden , you can layer them between sheets of waxed paper', \"make 2 more ruffles across the top of the pan , using the previously scraped area as your guide -- the left-hand corner of chocolate will be your 12 o'clock point and the cleaned-off section of the pan your edge , or end point\", 'make the next three ruffles just below",
      'then turn the pan around to get to the chocolate on the bottom and make three more\', "with practice -- and ruffling takes lots of practice -- you\'ll get 9 ruffles from each pan", "don\'t worry if you get fewer at the start", \'if , as sometimes happens , your ruffles crack or you get rolls of chocolate , not ruffles , it might be because the chocolate is too cold -- give it a few more minutes at room temperature before you try again\', "if the chocolate melts and gets gooey next to the spatula , it\'s too soft and needs a minute or two more in the refrigerator", "when the temperature is just right -- smooth and pliable -- but you still can\'t get a nicely fanned ruffle , angle the blade differently as you scrape", \'for the syrup:',
      'bring the water and sugar to the boil in a small saucepan , stirring to dissolve the sugar , and simmer for 2 to 3 minutes',
      'remove from the heat and cool',
      "add 1 / 4 cup of the eau-de-vie', \"taste the syrup and decide if you'd like a little more of the liqueur\", 'set aside",
      'for filling and wrap',
      'beat the creme fraiche with the vanilla extract to soft peaks , then add 2 tbsp of the sugar , beating until thickened',
      'taste and add more sugar if you want it , then continue to beat until the cream just begins to stiffen',
      'cover and keep refrigerated until needed',
      'assembling the cake -- cut the cooled genoise into 3 even layers with a long serrated knife',
      'fit one layer into the bottom of a high-sided 8-inch round cake pan with a removable bottom or an 8-inch springform pan and brush the layer with syrup',
      'place the chopped chocolate in a small bowl and whisk in the boiling water until the chocolate is fully melted and smooth',
      'switch to a rubber spatula and folds 1 / 4 cup of the creme fraiche into the chocolate',
      'fold in another cup of the creme fraiche and then quickly , before it hardens , spread the chocolate creme fraiche evenly over the genoise layer in the pan',
      'moisten the second layer of genoise with syrup and set it , moistened side down , in the pan , pressing gently to level it on the chocolate creme fraiche',
      'moisten the top of the layer with some of the syrup and top with an even layer of fresh raspberries , leaving just a bit of space between each berry',
      'keep 1 perfect berry in reserve',
      'beat the remaining creme fraiche until it holds its shape',
      'spoon 1 to 2 cups of the creme fraiche over the berries and , using an offset spatula , delicately smooth the creme fraiche over and between the berries',
      'moisten the remaining layer of genoise with syrup and set it , moistened side down , into the pan , again pressing lightly to set it in place',
      'chilling the cake -- cover the cake and the remaining creme fraiche with plastic and refrigerate for at least 2 to 3 hours , or up to 24 hours',
      'run a knife around the sides of the cake , then release and remove the pan or the ring of the springform pan',
      'put the cake , still on its pan bottom , on a large piece of parchment paper and set the cake on a decorating turntable , a lazy susan , or a large inverted cake pan',
      'making the wrap -- using ridged plastic shelf liner , freezer paper , or 500 mylar , cut a strip 26 inches long and 3 / 8 inch wider than the height of the finished cake , about 3 inches',
      'place a larger piece of waxed paper on the counter in front of you --this is your drip sheet -- and put the strip on the waxed paper',
      'melt the chocolate in the top of a double boiler set over an inch of barely simmering water or in a microwave oven set at medium power , stirring chocolate once or twice until melted and smooth',
      'the chocolate should be between 115f to 120f pour the chocolate down the center of the strip , spreading it with an offset spatula across the entire strip and beyond -- let it run over a bit onto the waxed paper',
      'slip the point of a small knife under one edge of the chocolate-coated strip and grab the edges of the strip with your fingers',
      'slide your free hand under the strip and grab the other end',
      'lift the strip and fit it neatly around the cake , positioning it so that the chocolate side is against the cake',
      'press one end against the cake and leave the other end standing away from the cake at the point where it would overlap if you pressed it closed',
      'slip a small piece of waxed paper into this spot , just to hold your place',
      'assembly and finishing',
      'chilling the wrapped cake -- refrigerate the cake of at least 1 hour , until the chocolate hardens',
      "finishing the wrapped cake -- place the cake on the decorating turntable and spread the remained creme fraiche over the top , spreading it out to the edge of the band', \"remove the chocolate ruffles from the refrigerator and , beginning at the outside edge , arrange the ruffles in a circle , planting them gently in the creme fraiche and allowing their frilly edges to extend beyond the cake's rim\", 'continue to arrange the ruffles in slightly overlapping concentric circles until the creme fraiche is covered",
      'put the reserved perfect raspberry in the center of the cake and chill the cake for about 15 minutes , until firm , before removing the plastic and serving',
      'to remove the plastic on the chocolate band , discard the waxed paper "place keeper" and peel away an inch of the plastic from the end of the band attached to the cake',
      'put a dollop of melted chocolate on that end to act as glue and overlap the other end of the band , pressing lightly to seal it',
      'carefully remove the plastic',
      'if the plastic sticks , put the cake back in the refrigerator for about 10 minutes , then try again',
      "to cut the cake , dip a long sharp serrated knife into hot water , wipe it dry , and cut straight down', \"since the first piece is often difficult to remove , it's best to make it a generous , easier-to-remove slice\", 'storing -- although the parts of the cake can be made well in advance , the assembled cake should be served the day it is made",
    ],

    ingredients: [
      'unsalted butter',
      'pure vanilla extract',
      'all-purpose flour',
      'unsweetened cocoa powder',
      'eggs',
      'sugar',
      'bittersweet chocolate',
      'water',
      'eau de vie',
      'creme fraiche',
      'semisweet chocolate',
      'boiling water',
      'fresh raspberries',
    ],
  },
  {
    id: 81,
    recipeName: 'easy yeast bread with variations    ',
    cookTime: 210,
    description:
      'found online in response to a request and now posted by request.  the blurb that accompanied it read as follows:  "the following came from a pamphlet of the same title i picked up in the baking supplies aisle of a krogers in either kalamazoo or battle creek about 25 years ago. i\'ve used every variation and facet of the instructions and had nothing but success! my faves are the rye breads.  unlimited variety from these basic recipes!"  i have not tried this recipe so times and servings are a guess-timate.  a lot of directions but then... a lot of variations to try.',
    steps: [
      'white bread:',
      'lightly spooning flour into measuring cup & leveling off , measure out 2 1 / 2 cups flour',
      'combine flour , dry yeast , sugar , & salt in a large mixer bowl',
      'blend',
      'in a medium saucepan , combine water , milk , and oil',
      'heat until very warm',
      'add eggs and liquid to flour mixture',
      'mixing - blend at low speed until moistened',
      'beat 3 minutes at medium speed',
      'with a wooden spoon , stir in an additional 3 to 3-1 / 2 cups of flour to form a sticky dough',
      'in bowl or on a floured board , gradually work in 1 / 2 to 1-1 / 2 cups more flour , kneading or working in with hands until dough is smooth , pliable and no longer sticky',
      'rising - place dough in a greased bowl',
      'cover with a cloth or loose fit lid',
      'let rise in a warm place until light and double in size , about 45 minutes',
      'shaping & baking:punch down dough to remove air bubbles',
      'divide dough into two parts',
      'from dough into desired shapes',
      'place in greased pans according to shaping and baking directions',
      'cover , let rise in a warm place until light and doubled in size , about 30 minutes',
      'bake at 375f according to shape until loaf sounds hollow when lightly tapped',
      'immediately remove from pans',
      'cool',
      'whole wheat bread -',
      'follow white bread recipe',
      'after beating with mixer , stir in 3 cups of whole wheat flour in stead of white , knead in 3 / 4 to 1-1 / 4 cups white flour',
      'medium rye bread -',
      'follow white bread recipe',
      'after beating with mixer , stir in 3 cups medium rye flour instead of white flour',
      'knead in 1-1 / 4 to 1-3 / 4 cups white flour',
      'rye dough should not completely double in size',
      'add 1 tbsp freshly crushed caraway seeds with rye flour',
      'decrease the first rising periods by 15 minutes each',
      '-----',
      'ingredient variations',
      'ingredients stirred in are added with the flour as it is stirred inches',
      'honey / molasses: substitute 1 / 4 cup for sugar',
      'reduce milk to 3 / 4 cup',
      'brown sugar: substitute 1 / 4 cup for the white sugar',
      'rolled oats: stir in 1 / 2 cup',
      'wheat germ: stir in 1 / 2 cup',
      'cheese: stir in 1 cup shredded cheddar , american , monterey jack or swiss cheese',
      'herbs & spices: stir in 1 / 4 to 1 / 2 tsp celery seed or dill weed , or 1 / 2 tsp italian seasoning , or 2 tbsp minced chives , caraway or sesame seeds',
      'onion: stir in 1 / 2 cup , finely chopped',
      'raisins / chopped dates or other dried fruit: use sweet dough recipe',
      'stir in 1-1 / 2 cups fruit',
      '-----',
      'specialty white bread variations -',
      'french bread: reduce sugar to 1 tbsp',
      'omit milk and eggs',
      'use 2 cups water',
      'reduce stirred in flour to 1-1 / 2 to 2 cups',
      'increase first rise to 1 hour',
      'shape and bake according to shaping and baking directions',
      'french loaf or rolls: brush with beaten egg just before baking',
      '-----',
      'rich egg bread - increase sugar to 1 / 3 cup',
      'decrease water to 3 / 4 cup',
      'use 3 eggs',
      '-----',
      'south of the border loaf - decrease sugar to 1 tablespoons decrease milk to 1 / 2 cup',
      'increase stirred in flour to 3-1 / 2 to 4 cups',
      'with this flour , stir in the following: 1 / 2 cup sour cream , 1 / 2 cup chopped olives , 1 / 2 cup chopped onion , 1 cup shredded cheddar or monterey jack cheese , 1 / 4 tsp garlic powder , 1 to 4 tbsp minced green chilies',
      'shape and bake according to directions for regular or round loaves , or rolls',
      '-----',
      'sweet dough - increase sugar to 1 / 2 cup',
      'eliminate water',
      'use 2 cups milk',
      'substitute butter or margarine for oil',
      'cinnamon swirl - pat each half of dough into a 7x14-inch rectangle',
      'spread with 1 tbsp butter or margarine',
      'combine 1 / 2 cup sugar and 2 tbsp cinnamon',
      'sprinkle half of mixture over each rectangle',
      'starting with the 7-inch side , roll jelly-roll style',
      'seal all edges tightly',
      'shape and bake according to instructions for a regular loaf',
      '-----',
      'specialty dark bread variations -',
      'delicatessen rye bread - (use basic med-rye recipe} omit sugar , water and 1 egg',
      'for warm liquid , heat 1-3 / 4 cups milk , 1 / 4 cup molasses , 1 / 4 cup cooking oil and 1 square unsweetened chocolate',
      'along with stirred in flour at 1 tbsp caraway seed stir in 1 / 4 to 1 cup white flour with the rye flour',
      'do let the dough to rise until double',
      'increase first rise to about 1 hour and the second to about 40 minutes',
      'increase the baking temperature to 400f',
      'bake loaves 30-40 minutes',
      'hearty whole wheat loaves - substitute 1 / 4 cup brown sugar for the white sugar',
      'along with the stirred in flour add 1 / 2 cup each wheat germ and rolled oats and 2 tbsp sesame seeds',
      'decrease kneaded in white flour to 1 / 4 to 3 / 4 cup',
      'increase first rise to about 1 hour',
      'light pumpernickel bread - eliminate sugar',
      'decrease water to 3 / 4 cup',
      'heat 1 / 4 cup molasses with other liquids',
      'along with stirred in flour add 2 tbsp caraway seeds',
      '100% whole wheat bread - eliminate white flour',
      'stir in 3 to 3-1 / 2 cups whole wheat flour',
      'knead in a further 1 / 2 to 1-1 / 2 cups whole wheat flour',
      '----------------------',
      'shaping and baking: use half of dough to make each shape',
      'using solid shortening , generously grease pans',
      'if desired , just before baking , slash top of loaf in any design using a sharp knife',
      'bake breads at 375f: [u]all loaves[ / u] - 35 to 45 minutes or until loaf sounds hollow when lightly tapped',
      'all rolls - 10 to 20 minutes',
      'regular loaf: use a 9x5 or 8x4-inch loaf pan',
      'press dough into pan',
      'insert fingers between pan and dough to round edges',
      'round loaf: use an 8 or 9-inch round cake pan , 1-1 / 2 quart round casserole or cookie sheet',
      'form dough into round ball',
      'flatten slightly',
      'french & oblong loaf:',
      'french: form dough into 14-inch loaf',
      'taper ends',
      'oblong: form dough into 8 to 10-inch oblong loaf',
      'round ends',
      'rope shaped loaves: shape half of dough into a 26-inch rope',
      'form into any desired shape described below',
      'coil: use 8 or 9-inch round cake pan , 1-1 / 2 quart round casserole or cookie sheet',
      'beginning at center of loaf , roll rope into snail shape',
      'tuck tail under',
      'twist: use a 9x5 or 8x4-inch loaf pan or cookie sheet',
      'cut rope in half to form two 13-inch ropes',
      'twist together',
      'seal ends',
      'figure eight: use a 9x5 or 8x4-inch loaf pan or cookie sheet',
      'form rope into figure-eight',
      'seal ends',
      'doughnut: use cookie sheet',
      'form circle by bringing ends of rope together',
      'seal',
      'flatten circle to 1-1 / 2 inch thickness',
      'rolls -',
      'round: form dough into 12 2-inch balls',
      'vienna: from dough into eight 6-inch oval rolls',
      'flatten slightly',
      'breadsticks: cut dough into walnut size pieces',
      'roll with hands into 5-inch sticks',
      'bread glazes - use any of the following glazes to create different crusts',
      'soft buttery crusts: brush loaves with softened or melted butter or margarine after baking',
      'crisp shiny crust: brush loaves with a mixture of 1 egg and 1 tbsp water just before baking',
      'may be sprinkled with poppy or sesame seed',
      'delicatessen crust: remove loaves from oven 5 minutes before done',
      'brush with a mixture of 1 / 2 tsp cornstarch and 1 / 4 cup water that has been heated to boiling',
      'return to oven to finish baking',
      'cinnamon / sugar crust: brush loaves with 2 tbsp melted butter or margarine',
      'sprinkle with mixture of 2 tbsp sugar and 1 / 2 tsp cinnamon after baking',
      'slightly crisp , shiny sweet crust: brush loaves with a mixture of 1 tbsp each of sugar and water after baking',
      'from:',
    ],

    ingredients: [
      'all-purpose flour',
      'dry yeast',
      'sugar',
      'salt',
      'water',
      'milk',
      'cooking oil',
      'eggs',
    ],
  },
]
export const NETWORK_DATA = [
  {
    user_id: 0,
    nodes: [
      { id: 'User ID', group: 1 },
      { id: 'rec1', group: 2 },
      { id: 'rec2', group: 2 },
      { id: 'rec3', group: 2 },
      { id: 'rec4', group: 2 },
      { id: 'rec5', group: 2 },
      { id: 'rec11', group: 2 },
      { id: 'rec12', group: 2 },
      { id: 'rec13', group: 2 },
      { id: 'rec21', group: 2 },
      { id: 'rec22', group: 2 },
      { id: 'rec23', group: 2 },
      { id: 'rec31', group: 2 },
      { id: 'rec32', group: 2 },
      { id: 'rec33', group: 2 },
      { id: 'rec41', group: 2 },
      { id: 'rec42', group: 2 },
      { id: 'rec43', group: 2 },
      { id: '137739', group: 3 },
      { id: '45', group: 3 },
      { id: '81', group: 3 },
    ],
    links: [
      { source: 'User ID', target: 'rec1', value: 1 },
      { source: 'User ID', target: 'rec2', value: 1 },
      { source: 'User ID', target: 'rec3', value: 1 },
      { source: 'User ID', target: 'rec4', value: 1 },
      { source: 'User ID', target: 'rec5', value: 1 },
      { source: 'rec1', target: 'rec11', value: 2 },
      { source: 'rec1', target: 'rec12', value: 2 },
      { source: 'rec1', target: 'rec13', value: 2 },
      { source: 'rec2', target: 'rec21', value: 2 },
      { source: 'rec2', target: 'rec22', value: 2 },
      { source: 'rec2', target: 'rec23', value: 2 },
      { source: 'rec3', target: 'rec31', value: 2 },
      { source: 'rec3', target: 'rec32', value: 2 },
      { source: 'rec3', target: 'rec33', value: 2 },
      { source: 'rec4', target: 'rec41', value: 2 },
      { source: 'rec4', target: 'rec42', value: 2 },
      { source: 'rec4', target: 'rec43', value: 2 },
      { source: 'rec5', target: '137739', value: 3 },
      { source: 'rec5', target: '45', value: 3 },
      { source: 'rec5', target: '81', value: 3 },
    ],
  },
  {
    user_id: 5000,
    nodes: [
      { id: 'User ID', group: 1 },
      { id: 'rec1', group: 2 },
      { id: 'rec2', group: 2 },
      { id: 'rec3', group: 2 },
      { id: 'rec4', group: 2 },
      { id: 'rec5', group: 2 },
      { id: '45', group: 3 },
      { id: '81', group: 3 },
      { id: 'rec31', group: 2 },
      { id: 'rec41', group: 2 },
      { id: '137739', group: 2 },
    ],
    links: [
      { source: 'User ID', target: 'rec1', value: 1 },
      { source: 'User ID', target: 'rec2', value: 1 },
      { source: 'User ID', target: 'rec3', value: 1 },
      { source: 'User ID', target: 'rec4', value: 1 },
      { source: 'User ID', target: 'rec5', value: 1 },
      { source: 'rec1', target: '45', value: 3 },
      { source: 'rec2', target: '81', value: 3 },
      { source: 'rec3', target: 'rec31', value: 2 },
      { source: 'rec4', target: 'rec41', value: 2 },
      { source: 'rec5', target: '137739', value: 2 },
    ],
  },
  {
    user_id: 1000,
    nodes: [
      { id: 'User ID', group: 1 },
      { id: 'rec1', group: 2 },
      { id: 'rec2', group: 2 },
      { id: 'rec3', group: 2 },
      { id: 'rec11', group: 2 },
      { id: 'rec12', group: 2 },
      { id: 'rec13', group: 2 },
      { id: 'rec21', group: 2 },
      { id: '137739', group: 3 },
      { id: '45', group: 3 },
      { id: '81', group: 3 },
    ],
    links: [
      { source: 'User ID', target: 'rec1', value: 1 },
      { source: 'User ID', target: 'rec2', value: 1 },
      { source: 'User ID', target: 'rec3', value: 1 },
      { source: 'rec1', target: 'rec11', value: 2 },
      { source: 'rec1', target: 'rec12', value: 2 },
      { source: 'rec1', target: 'rec13', value: 2 },
      { source: 'rec2', target: 'rec21', value: 2 },
      { source: 'rec2', target: '81', value: 2 },
      { source: 'rec2', target: '45', value: 2 },
      { source: 'rec3', target: '137739', value: 2 },
    ],
  },
]
